### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by Swetlana-K** [timo9067/amazon-expenses-tracker-g5#14]
When attempting to start our program, I encountered the following errors:
1. When starting the program in the command line, the entered username and password are ignored. It prompts to select a username and password.
 2. After entering the username, it prompts to change the password, although it has not been entered yet.
3. A username with only 2 letters is accepted.
4. When logging in, the previously entered user data is not recognized for the first three attempts. Only after the fourth attempt does the login work.
5.  After the greeting "Amazon Purchase Tracking Utility," the user is prompted again for the username, password, and phone number.
6. After the announcement "Congratulations! You are successfully registered!", the program asks for the username and password again.

**Comment by timo9067** [comment]
I did not upload the changed login.py and registration.py
